ProjectShopManagment/Controllers/ManageRoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using ProjectShopManagment.Models;
using ProjectShopManagment.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectShopManagment.Controllers
{
    public class ManageRoleController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: ManageRole
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RolesVM roles)
        {
            try
            {
                var role = new IdentityRole
                {
                    Name = roles.Name
                };
                db.Roles.Add(role);
                if (db.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                ViewBag.result = ex.Message;
            }
            return View(roles);
        }
        [HttpGet]
        public ActionResult AssignRole()
        {
            ViewBag.Userlist = db.Users.Select(s => new SelectListItem
            { Text = s.UserName, Value = s.Id });
            ViewBag.RoleList = db.Roles.Select(s => new SelectListItem
            { Text = s.Name, Value = s.Name });
            return View();
        }
        [HttpPost]
        public ActionResult AssignRole(string Userlist,string RoleList)
        {
            ViewBag.Userlist = db.Users.Select(s => new SelectListItem
            { Text = s.UserName, Value = s.Id });
            ViewBag.RoleList = db.Roles.Select(s => new SelectListItem
            { Text = s.Name, Value = s.Name });

            var store = new UserStore<ApplicationUser>(db);
            var uManager = new UserManager<ApplicationUser>(store);
            IdentityResult result = uManager.AddToRole(Userlist, RoleList);
            if (result.Succeeded)
            {
                ViewBag.result = "Successfully assigned role";
            }
            else
            {
                ViewBag.result = "Failed";
            }
            return View();
        }
        public ActionResult UserRole()
        {
            ViewBag.Userlist = db.Users.Select(s => new SelectListItem
            { Text = s.UserName, Value = s.Id });
            return View();
        }
        [HttpPost]
        public ActionResult UserRole(string Userlist)
        {
            ViewBag.Userlist = db.Users.Select(s => new SelectListItem
            { Text = s.UserName, Value = s.Id });

            var store = new UserStore<ApplicationUser>(db);
            var uManager = new UserManager<ApplicationUser>(store);
            if (!String.IsNullOrEmpty(Userlist))
            {
                var roleList = uManager.GetRoles(Userlist);
                ViewBag.roles = new SelectList(roleList);
            }
            else
            {
                ViewBag.result = "Provide User id";
            }
            return View();
        }

        public ActionResult GetUsersRole()
        {
            IEnumerable<UsersRole> all = new List<UsersRole>();
            try
            {
                all = (from u in db.Users
                       select new
                       {
                           UserId = u.Id,
                           UserName = u.UserName,
                           RoleNames = (from ur in u.Roles
                                        join r in db.Roles
                                        on ur.RoleId equals r.Id
                                        select r.Name
                                      )
                       }).ToList().Select(s => new UsersRole
                       {
                           UserID = s.UserId,
                           UserName = s.UserName,
                           RoleName = string.Join(",", s.RoleNames)
                       }

                     );
            }
            catch(Exception ex)
            {
                ViewBag.result = ex.Message;
            }
            return View(all);
        }
        public ActionResult RemoveUsersRole()
        {
            ViewBag.Userlist = db.Users.Select(s => new SelectListItem
            {
                Text = s.UserName,
                Value = s.Id
            });
            ViewBag.RoleList = db.Roles.Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id
            });
            return View();
        }
        [HttpPost]
        public ActionResult RemoveUsersRole(string Userlist,string RoleList)
        {
            ViewBag.Userlist = db.Users.Select(s => new SelectListItem
            {
                Text = s.UserName,
                Value = s.Id
            });
            ViewBag.RoleList = db.Roles.Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id
            });
            var store = new UserStore<ApplicationUser>(db);
            var uManager = new UserManager<ApplicationUser>(store);
            IdentityResult result = uManager.RemoveFromRole(Userlist, RoleList);
            if (result.Succeeded)
            {
                ViewBag.result = "Remove successfully";
            }
            if (result.Errors.Count() > 0)
            {
                
            }
            return View();
        }
    }
}

ProjectShopManagment/Views/ManageRole/AssignRole.cshtml
@{
    ViewBag.Title = "AssignRole";
}

<h2>AssignRole</h2>

@if (ViewBag.result != null)
{

}

@using (Html.BeginForm())
{
    <div>
        <label>User</label>
        <div>
            @Html.DropDownList("Userlist",@ViewBag.Userlist as SelectList,"Select User")
        </div>
    </div>
    <div>
        <label>Role</label>
        <div>
            @Html.DropDownList("RoleList",@ViewBag.RoleList as SelectList,"Select Role")
        </div>
    </div>
    <div>
        <input type="submit" value="Assign"/>
    </div>
}

ProjectShopManagment/Views/ManageRole/Create.cshtml
@model ProjectShopManagment.ViewModel.RolesVM
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@if (ViewBag.result != null)
{
    <div>
        @ViewBag.result
    </div>

}

@using (Html.BeginForm())
{
    <div>
        <label>Name</label>
        @Html.EditorFor(m => m.Name)
    </div>
    <div>
        <input type="submit" value="Save" />
    </div>
}

ProjectShopManagment/Views/ManageRole/GetUsersRole.cshtml
@model IEnumerable<ProjectShopManagment.ViewModel.UsersRole>
@{
    ViewBag.Title = "GetUsersRole";
}

<h2>GetUsersRole</h2>

<table >
    <tr>
        <th>UserName</th>
        <th>Role Name</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.UserName</td>
            <td>@item.RoleName</td>
        </tr>
    }
</table>

ProjectShopManagment/Views/ManageRole/Index.cshtml
@using Microsoft.AspNet.Identity.EntityFramework
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Create", "Create", "ManageRole")

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>
            Name
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "ManageRole", new { id = item.Id }, null)||
                @Html.ActionLink("Delete", "Delete", "ManageRole", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>

ProjectShopManagment/Views/ManageRole/RemoveUsersRole.cshtml
@{
                /**/

                ViewBag.Title = "RemoveUsersRole";
}

<h2>RemoveUsersRole</h2>

@if (ViewBag.result != null)
{
    <div class="alert-danger">
        @ViewBag.result
    </div>
}

@using (Html.BeginForm())
{
    <div>
        <label>User</label>
        <div>
            @Html.DropDownList("Userlist", ViewBag.Userlist as SelectList, "Select User")
        </div>
    </div><div>
        <label>User</label>
        <div>
            @Html.DropDownList("RoleList", @ViewBag.RoleList as SelectList, "Select User")
        </div>
    </div>
    <div>
        <input type="submit" value="Remove" class="btn btn-primary" />
    </div>
}

ProjectShopManagment/Views/ManageRole/UserRole.cshtml
@{
    ViewBag.Title = "UserRole";
}

<h2>UserRole</h2>


@using (Html.BeginForm())
{
    <div>
        <label>User</label>
        <div>
            @Html.DropDownList("Userlist",@ViewBag.Userlist as SelectList,"Select User")
        </div>
    </div>
    <div>
        <input type="submit"value="Get Role"/>
    </div>
}
<div>
    <label>
        Role Name
    </label>
    @if (ViewBag.roles != null)
    {
        @Html.DropDownList("roles",null,"select")
    }
</div>