ProjectShopManagment/Models/Stall_Manager.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectShopManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Stall_Manager
    {
        public int ID { get; set; }
        public string ManagerName { get; set; }
        public string Email { get; set; }
        public Nullable<int> M_Stall { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public HttpPostedFileBase Imgfile { get; set; }

        public virtual Stall Stall { get; set; }
    }
}

ProjectShopManagment/Controllers/Stall_ManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

using ProjectShopManagment.Models;

namespace ProjectShopManagment.Controllers
{
    public class Stall_ManagerController : Controller
    {
        private DbShoppingMallEntities db = new DbShoppingMallEntities();
       [Authorize(Roles ="admin")]
        // GET: Stall_Manager
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            
                
                ViewBag.NameSortParam = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.StallSortParam = sortOrder == "stall" ? "stall_desc" : "stall";
                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }
                ViewBag.CurrentFilter = searchString;
                var manager = from s in db.Stall_Manager select s;

                if (!String.IsNullOrEmpty(searchString))
                {
                    manager = manager.Where(s => s.ManagerName.ToUpper().Contains(searchString.ToUpper()));
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        manager = manager.OrderByDescending(s => s.ManagerName);
                        break;
                    case "stall_desc":
                        manager = manager.OrderByDescending(s => s.Stall.StallName);
                        break;
                    case "stall":
                        manager = manager.OrderBy(s => s.Stall.StallName);
                        break;
                    default:
                        manager = manager.OrderBy(s => s.ManagerName);
                        break;
                }
                ViewBag.CurrentSort = sortOrder;
                int pageSize = 5;
                int pageNumber = (page ?? 1);
          
            var stall_Manager = db.Stall_Manager.Include(s => s.Stall);
            return View(manager.ToPagedList(pageNumber, pageSize));
           
        }

        // GET: Stall_Manager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stall_Manager stall_Manager = db.Stall_Manager.Find(id);
            if (stall_Manager == null)
            {
                return HttpNotFound();
            }
            return View(stall_Manager);
        }

        // GET: Stall_Manager/Create
        public ActionResult Create()
        {
            ViewBag.M_Stall = new SelectList(db.Stalls, "ID", "StallName");
            return View();
        }

        // POST: Stall_Manager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/*[Bind(Include = "ID,ManagerName,Email,M_Stall,Image")]*/ Stall_Manager stall_Manager)
        {
           
            if (ModelState.IsValid)
            {
                if (stall_Manager.Imgfile != null)
                {
                    string ext = Path.GetExtension(stall_Manager.Imgfile.FileName).ToLower();
                    if (ext == ".jpg" || ext == ".png" || ext == ".jpeg")
                    {
                        string fname = Path.GetFileNameWithoutExtension(stall_Manager.Imgfile.FileName) + "_" + Guid.NewGuid().ToString() + ext;
                        stall_Manager.Imgfile.SaveAs(Path.Combine(Server.MapPath("~/Upload"), fname));
                        stall_Manager.Image = "~/Upload/" + fname;
                    }
                }
                db.Stall_Manager.Add(stall_Manager);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.M_Stall = new SelectList(db.Stalls, "ID", "StallName", stall_Manager.M_Stall);
            return View(stall_Manager);
        }

        // GET: Stall_Manager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stall_Manager stall_Manager = db.Stall_Manager.Find(id);
            if (stall_Manager == null)
            {
                return HttpNotFound();
            }
            ViewBag.M_Stall = new SelectList(db.Stalls, "ID", "StallName", stall_Manager.M_Stall);
            return View(stall_Manager);
        }

        // POST: Stall_Manager/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/*[Bind(Include = "ID,ManagerName,Email,M_Stall,Image")]*/ Stall_Manager stall_Manager)
        {
            
            if (ModelState.IsValid)
            {
                if (stall_Manager.Imgfile != null)
                {
                    string ext = Path.GetExtension(stall_Manager.Imgfile.FileName).ToLower();
                    if (ext == ".jpg" || ext == ".png" || ext == ".jpeg")
                    {
                        string fname = Path.GetFileNameWithoutExtension(stall_Manager.Imgfile.FileName) + "_" + Guid.NewGuid().ToString() + ext;
                        stall_Manager.Imgfile.SaveAs(Path.Combine(Server.MapPath("~/Upload"), fname));
                        stall_Manager.Image = "~/Upload/" + fname;
                    }
                }
                db.Entry(stall_Manager).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.M_Stall = new SelectList(db.Stalls, "ID", "StallName", stall_Manager.M_Stall);
            return View(stall_Manager);
        }

        // GET: Stall_Manager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stall_Manager stall_Manager = db.Stall_Manager.Find(id);
            if (stall_Manager == null)
            {
                return HttpNotFound();
            }
            return View(stall_Manager);
        }

        // POST: Stall_Manager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stall_Manager stall_Manager = db.Stall_Manager.Find(id);
            db.Stall_Manager.Remove(stall_Manager);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectShopManagment/Views/Stall_Manager/Create.cshtml
@model ProjectShopManagment.Models.Stall_Manager

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Stall_Manager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Stall_Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.M_Stall, "M_Stall", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("M_Stall", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.M_Stall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Imgfile" name="Imgfile" />
                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectShopManagment/Views/Stall_Manager/Delete.cshtml
@model ProjectShopManagment.Models.Stall_Manager

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stall_Manager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stall.StallName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stall.StallName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectShopManagment/Views/Stall_Manager/Details.cshtml
@model ProjectShopManagment.Models.Stall_Manager

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Stall_Manager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stall.StallName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stall.StallName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectShopManagment/Views/Stall_Manager/Edit.cshtml
@model ProjectShopManagment.Models.Stall_Manager

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Stall_Manager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Stall_Manager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManagerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManagerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.M_Stall, "M_Stall", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("M_Stall", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.M_Stall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="ImgFile" name="ImgFile" />
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectShopManagment/Views/Stall_Manager/Index.cshtml
@model PagedList.IPagedList<ProjectShopManagment.Models.Stall_Manager>
@using PagedList.Mvc
@using PagedList
<link href="~/Content/PagedList.css" rel="stylesheet" />
@{

    ViewBag.Title = "Index";
}

<h2>All Stall Manager</h2>
<div>
    @ViewBag.result;
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Stall_Manager", FormMethod.Get))
{
    <p>
        Search by  Name:@Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table table-bordered table-hover table-condensed">
    <tr >
        <th>
            @*@Html.DisplayNameFor(model => model.ManagerName)*@
            @Html.ActionLink("ManagerName", "Index", "Stall_Manager", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Email)*@
            Email
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Image)*@
            Image
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Stall.StallName)*@
            @Html.ActionLink("Stall Name", "Index", "Stall_Manager", new { sortOrder = ViewBag.StallSortParam, currentFilter = ViewBag.CurrentFilter }, null)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @if (item.Image != null)
                {
                    <img src="@Url.Content(item.Image)" height="60" width="70" />
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Stall.StallName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>
<br />
@Html.PagedListPager(Model, page => Url.Action("Index", new { page,
    sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))