ProjectShopManagment/Controllers/StallsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectShopManagment.Models;
using PagedList;

namespace ProjectShopManagment.Controllers
{
    public class StallsController : Controller
    {
        private DbShoppingMallEntities db = new DbShoppingMallEntities();

        // GET: Stalls
        public ActionResult Index(int?page)
        {
            var stalls = db.Stalls.Include(s => s.Floor);
            
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            
            return View(stalls.OrderBy(s=>s.StallNo).ToPagedList(pageNumber,pageSize));
        }

        // GET: Stalls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stall stall = db.Stalls.Find(id);
            if (stall == null)
            {
                return HttpNotFound();
            }
            return View(stall);
        }

        // GET: Stalls/Create
        public ActionResult Create()
        {
            ViewBag.S_Floor = new SelectList(db.Floors, "ID", "F_Level");
            return View();
        }

        // POST: Stalls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,StallNo,StallName,StallVolume,S_Floor")] Stall stall)
        {
            if (ModelState.IsValid)
            {
                db.Stalls.Add(stall);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.S_Floor = new SelectList(db.Floors, "ID", "F_Level", stall.S_Floor);
            
            return View(stall);
        }

        // GET: Stalls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stall stall = db.Stalls.Find(id);
            if (stall == null)
            {
                return HttpNotFound();
            }
            ViewBag.S_Floor = new SelectList(db.Floors, "ID", "F_Level", stall.S_Floor);
            return View(stall);
        }

        // POST: Stalls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,StallNo,StallName,StallVolume,S_Floor")] Stall stall)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stall).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.S_Floor = new SelectList(db.Floors, "ID", "F_Level", stall.S_Floor);
            return View(stall);
        }

        // GET: Stalls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stall stall = db.Stalls.Find(id);
            if (stall == null)
            {
                return HttpNotFound();
            }
            return View(stall);
        }

        // POST: Stalls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stall stall = db.Stalls.Find(id);
            db.Stalls.Remove(stall);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectShopManagment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Stall", "Index", "Stalls")</li>
                    <li>@Html.ActionLink("Manager", "Index", "Stall_Manager")</li>
                    <li>@Html.ActionLink("Employee", "Index", "Employees")</li>
                    <!--<li class="dropdown btn-group nav">
                        <button type="button" class="btn navbar-btn" style="background-color:forestgreen">-->@*@User.Identity.Name*@ <!--Role</button>
                        <button type="button" class="btn navbar-btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Role", "Index", "ManageRole")</li>

                            <li>@Html.ActionLink("Assign Role", "AssignRole", "ManageRole")</li>
                            <li>@Html.ActionLink("UserRole", "UserRole", "ManageRole")</li>
                            <li>@Html.ActionLink("User with Role", "GetUsersRole", "ManageRole")</li>
                            <li>@Html.ActionLink("Remove UserRole", "RemoveUsersRole", "ManageRole")</li>
                        </ul>

                    </li>-->
                    <li></li>
                    <li class="dropdown btn-group nav navbar-right" style="margin-left:5px;">
                        <button type="button" class="btn navbar-btn" style="background-color:forestgreen">@*@User.Identity.Name*@Profile</button>
                        <button type="button" class="btn navbar-btn dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("My Profile", "Index", "Profiles")</li>
                        </ul>
                    </li>


                </ul>
                @Html.Partial("_LoginPartial")
                @*@if (Request.IsAuthenticated)
                {
                    @Html.Partial("pic")
                }*@

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectShopManagment/Views/Shared/pic.cshtml
@model ProjectShopManagment.ViewModel.ProfileVM
@if (Model.Picture != null)
{
    @*<img src="@Url.Content(Model.Picture)" alt="no picture" width="70" height="70" />*@
}